import { NcMenu } from '../interfaces/menu';
import * as fs from 'fs-extra';

/**
 * 生成菜单
 *
 * @export
 * @param {string} genDir
 * @param {NcMenu[]} menus
 */
export function generateMenu(genDir: string, menus: NcMenu[]) {
  fs.writeFileSync(
    `${genDir}/app.menus.ts`,
    `/* DO NOT EDIT, file generated by ng-nest */
import { AppMenu } from '@interfaces';
export const menus: AppMenu[] = ${JSON.stringify(menus, null, 2)}`,
    'utf8'
  );
}
