import { writeFileSync } from 'fs-extra';
import { NcCore } from '../interfaces/core';

/**
 * 生成 core 中类型文件，json 格式
 *
 * @export
 * @param {string} genDir
 * @param {NcCore} core
 */
export function generateCore(genDir: string, lang: string, core: NcCore) {
  writeFileSync(
    `${genDir}/${lang}-docs.types.ts`,
    `/* DO NOT EDIT, file generated by ng-nest */
export default ${JSON.stringify(core, null, 2)}`,
    'utf8'
  );
}
