import { writeFileSync } from 'fs-extra';
import { NcCore } from '../interfaces/core';
import { NcProp } from '../interfaces/prop';

/**
 * 生成 core 中类型文件，json 格式
 *
 * @export
 * @param {string} genDir
 * @param {NcCore} core
 */
export function generateCore(genDir: string, lang: string, core: NcCore) {
  const types: { [key: string]: NcProp } = {};
  for (let item of core) {
    types[item.name] = item;
  }
  writeFileSync(
    `${genDir}/${lang}-docs.types.ts`,
    `/* DO NOT EDIT, file generated by ng-nest */
import { AppProp } from "./core.interface";

export const ${lang}: {[key: string]: AppProp} = ${JSON.stringify(types, null, 2)}`,
    'utf8'
  );
}
