# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    - name: checkout
      uses: actions/checkout@master
    
    - name: use node.js
      uses: actions/setup-node@v1
      with: 
        node-version: 16.13.0
    
    - name: build
      run: |
        npm install
        npm run test:ng-nest-ui -- --configuration=ci
